name: CI

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
    paths-ignore: [ "**.md", "**.adoc" ]
  pull_request:
    branches: [ "**" ]
    paths-ignore: [ "**.md", "**.adoc" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - { CXX: g++, CC: gcc }
          - { CXX: clang++, CC: clang }
        backend: [ibus, fcitx]

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y             build-essential             clang             cmake             ninja-build             pkg-config             rustc             cargo             libzstd-dev             qtbase5-dev             qtbase5-dev-tools             libqt5svg5-dev             libibus-1.0-dev             libfcitx5core-dev

      - name: Configure
        env:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          BACKEND: ${{ matrix.backend }}
        run: |
          if [ "${BACKEND}" = "ibus" ]; then
            cmake -S . -B build -G Ninja               -DENABLE_IBUS=ON               -DENABLE_FCITX=OFF
          else
            cmake -S . -B build -G Ninja               -DENABLE_IBUS=OFF               -DENABLE_FCITX=ON
          fi

      - name: Build
        run: cmake --build build --parallel 2
